project:
  type: website
  output-dir: docs

website:
  title: CPLN 6710 Statistical Data Mining Project Repositiory
  subtitle: Jenny Brar │ Maud Ceruso │ Shubhanga Satyal
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
